### ISSUE TITLE
Customizable timeout?

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/oxide.rs#120]
Some commands -- such as instance creation -- can take a hot second to complete.

Should they be async? Arguably yes. However, it would be nice to be able to customize the CLI to not drop the connection after a few seconds, to give these long-running operations room to succeed when they otherwise might not.

**Comment by david-crespo** [comment]
Or we could just have a really long timeout on everything.

**Comment by david-crespo** [comment]
Would bumping these to 60 be enough? Could even go higher.

https://github.com/oxidecomputer/oxide.rs/blob/91b373131fe993af30180f9fedd9d1165201dc7a/cli/src/context.rs#L60-L62

https://github.com/oxidecomputer/oxide.rs/blob/91b373131fe993af30180f9fedd9d1165201dc7a/cli/src/cmd_auth.rs#L104-L105

**Comment by askfongjojo** [comment]
Bumped this to FCS as the error will likely show up during user acceptance testing. (I've encountered this 100% of the time on rack2 when using ubuntu 22.04 and 20.04 for a moderate-sized VM.)

**Comment by askfongjojo** [comment]
Operation timed out error is no longer seen in CLI on commit `5756510ac1a272cb33c1d444750336037bd49b96`.
