### ISSUE TITLE
Can't provide IDP metadata

### ISSUE THREAD

**Issue by luqmana** [oxidecomputer/oxide.rs#162]
Similar to https://github.com/oxidecomputer/oxide.rs/issues/161, there's no way to pass `idp_metadata_source` with `oxide silo idp saml create`

```console
$ oxide silo idp saml create --help
Create a SAML IdP

Usage: oxide silo idp saml create [OPTIONS] --silo <silo> --acs-url <acs-url> --description <description> --idp-entity-id <idp-entity-id> --name <name> --slo-url <slo-url> --sp-client-id <sp-client-id> --technical-contact-email <technical-contact-email>

Options:
      --silo <silo>
          Name or ID of the silo
      --acs-url <acs-url>
          service provider endpoint where the response will be sent
      --description <description>

      --group-attribute-name <group-attribute-name>
          If set, SAML attributes with this name will be considered to denote a user's group membership, where the attribute value(s) should be a comma-separated list of group names.
      --idp-entity-id <idp-entity-id>
          idp's entity id
      --name <name>

      --slo-url <slo-url>
          service provider endpoint where the idp should send log out requests
      --sp-client-id <sp-client-id>
          sp's client id
      --technical-contact-email <technical-contact-email>
          customer's technical contact for saml configuration
  -h, --help
          Print help
```

**Comment by ahl** [comment]
The value of `idp_metadata_source` is
```rust
    pub enum IdpMetadataSource {
        #[serde(rename = "url")]
        Url { url: String },
        #[serde(rename = "base64_encoded_xml")]
        Base64EncodedXml { data: String },
    }
```

What if `oxide silo idp saml create` had two mutually exclusive options: `--url <URL> | --base64-encoded-xml <STRING>`?

Similarly we could have options for `--private-key` and `--public-cert` that could be used to specify the value of `signing_keypair`.

As a stopgap, `--json-body <FILE>` should work now.

**Comment by luqmana** [comment]
> What if `oxide silo idp saml create` had two mutually exclusive options: `--url <URL> | --base64-encoded-xml <STRING>`?

Yea, that would work. Only nit I'd have maybe is something more specific like `--metadata-url` since there are already a few other `--*-url` parameters it could be confused with.

> As a stopgap, `--json-body <FILE>` should work now.

Huh, didn't see that in that earlier. Must've been on an older build. Thanks!
