### ISSUE TITLE
CLI responds with an error when trying to view an image that has been promoted

### ISSUE THREAD

**Issue by karencfv** [oxidecomputer/oxide.rs#171]
Sadly this happens when trying to view an image that has been promoted to silo level :(
 
```console
$ ./target/debug/oxide image view --image 499090e2-8b57-4f7f-a508-2b4128b3885b
error
Invalid Response Payload: error decoding response body: invalid type: null, expected a UUID string at line 1 column 199
```

**Comment by ahl** [comment]
What's the `version` subcommand say? Can you check the response using the `api` subcommand?

In particular, are you running a CLI from before https://github.com/oxidecomputer/oxide.rs/commit/403644eed766a1bb9b20b983d26599804de97cbd?

**Comment by karencfv** [comment]
Ha! yes, after I built the CLI from the latest commit the command works fine. Sorry about that!

**Comment by ahl** [comment]
To be clear: we could certainly produce better error messages!
