### ISSUE TITLE
ensure that output is parseable as json

### ISSUE THREAD

**Issue by ahl** [oxidecomputer/oxide.rs#264]
Currently the CLI emits additional text such as "success". This causes tools such as `jq` to fail to parse the output.

CC @askfongjojo

**Comment by david-crespo** [comment]
Might be more future-proof and flexible to add a `--json` flag. I could imagine wanting the default display to emphasize human-readability, like a nice table. In that case you might want to leave unparseable stuff in the default output so nobody relies on it being JSON. This is how I've seen lots of CLIs do it.

**Comment by karencfv** [comment]
I like the idea of flags. I'm not sure about defaulting to human readable though. For as lot of infra work, JSON is preferable. It's probably better to let users themselves set a default on their config file.

**Comment by david-crespo** [comment]
This is done, right?

**Comment by ahl** [comment]
What is "done"... yeah. I think we can mark this done, but I intend to have options for different output formats. I'm also not quite sure what to output if the CLI invocation has no response value. Currently is prints `null` and that's clearly kind of busted...

**Comment by ahl** [comment]
See also #672
