### ISSUE TITLE
Release CLI binaries for commonly used operating systems at FCS

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/oxide.rs#266]
We probably want to allow customers to download the CLI client without having to build it themselves.

OS to cover:
- Linux
- MacOS
- Windows (low priority)

**Comment by ahl** [comment]
See #19

**Comment by askfongjojo** [comment]
Can trail FCS by a couple days (ideally customers don't have to generate the binaries themselves)

**Comment by ahl** [comment]
Fixed by #279
