### ISSUE TITLE
CLI client panicked during auth login when hosts.toml file does not exist 

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/oxide.rs#284]
My apologies for finding this late. I decided to start in a clean slate by renaming my `~/.config/oxide/hosts.toml` file. Then I ran into this when trying to create a device token:
```
$ unset OXIDE_TOKEN
$ env | grep OX
OXIDE_HOST=https://oxide.sys.rack2.eng.oxide.computer/
$ mv ~/.config/oxide/hosts.toml ~/.config/oxide/hosts.toml.bak
$ oxide auth login --host $OXIDE_HOST
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: host https://oxide.sys.rack2.eng.oxide.computer/ not found', cli/src/cli_builder.rs:232:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(9), ...)', cli/src/main.rs:59:10
```
The program expects to find all three of these lines in the `hosts.toml` file before it would let me authenticate:
```
["https://oxide.sys.rack2.eng.oxide.computer/"]
token = "oxide-token-0f95437d459ab7eabb71839a146d3eeb53191e19"
user = "39d31bd7-95b9-42a1-9ed9-74ddb0db4744"
```
(FWIW, I tried adding them one at a time to see what it was looking for but it required all of them.)

**Comment by ahl** [comment]
I only see this with `OXIDE_HOST` and `OXIDE_TOKEN` unset which is arguably an error--indeed, I don't think we particularly want users to specify `$OXIDE_HOST` unless they're already logged into multiple silos. I've changed the error to look like this:

```console
$ OXIDE_HOST=https://oxide.sys.rack2.eng.oxide.computer/ oxide auth login --host https://oxide.sys.rack2.eng.oxide.computer/
$OXIDE_HOST is set, but https://oxide.sys.rack2.eng.oxide.computer/ has no corresponding token.
Login without $OXIDE_HOST set or set $OXIDE_TOKEN.
```

**Comment by askfongjojo** [comment]
Ah ok, I didn't realize that the OXIDE_HOST environment variable is getting into the way. Thanks for debugging this and adding the error handling!
