### ISSUE TITLE
CLI: libssl1.1 dependency does not work for some customers

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/oxide.rs#295]
Customers who are up-to-date with OpenSSL cannot use binaries that are built with libssl1.1 dependency. As a workaround, they can build them on their own but ideally, we want to not pass that burden to the end-users.

**Comment by ahl** [comment]
I think as a more durable fix than #296 we'll want to use the `native-tls-vendored` feature of `reqwest`
