### ISSUE TITLE
add `current-user ssh-key generate` custom subcommand

### ISSUE THREAD

**Issue by ahl** [oxidecomputer/oxide.rs#30]
Crib https://github.com/oxidecomputer/cli/blob/main/src/cmd_ssh_key.rs#L134

**Comment by karencfv** [comment]
Started working on this and realised we're essentially re-writing ssh-keygen and then appending the `$ oxide current-user ssh-key create` command at the end. I'm not entirely convinced this is something we should be doing. I'm not clear as to why we need this command especially as we're trying to tell our users that they can do whatever we do on our clients through the API. 

What do you think @ahl ?

**Comment by karencfv** [comment]
Closing after having conversation with @ahl . It's not a high value feature
