### ISSUE TITLE
Update bundled OpenSSL to v111.27.0+1.1.1v

### ISSUE THREAD

**Issue by rmustacc** [oxidecomputer/oxide.rs#314]
We're behind a few releases of OpenSSL 1.1.1. We should probably bump the bundled version and at some point move to 3.x.

**Comment by ahl** [comment]
It looks like the the `openssl` crate has been on a year+ journey to get to 3.x (https://github.com/sfackler/rust-openssl/issues/1645) and that it may be close (https://github.com/sfackler/rust-openssl/pull/1925).
