### ISSUE TITLE
non-required POST body parameters ignored by progenitor

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/oxide.rs#34]
Currently not doing anything.

https://github.com/oxidecomputer/oxide-sdk-and-cli/blob/1403f6dfe489949ad239e1df32f246163e58a4f0/cli/src/generated_cli.rs#L9478-L9481

**Comment by ahl** [comment]
This is generally true of any non-required body parameter. The fix is going to be annoying, but I'm on it.
