### ISSUE TITLE
Need a new release of the CLI binaries that support BGP configurations

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/oxide.rs#430]
As part of this release, we can perhaps also drop the `-beta` label from the version name?

**Comment by karencfv** [comment]
At our last meeting @ahl mentioned wanting to make some changes to the way we store credentials and handle auth (please correct me if I'm wrong!). I'm not sure we want to drop the `-beta` just yet :thinking:

**Comment by ahl** [comment]
Made a release with a hand-built version with an older glibc: https://github.com/oxidecomputer/oxide.rs/releases/tag/v0.1.0
