### ISSUE TITLE
Better error message/checking for `Name`

### ISSUE THREAD

**Issue by labbott** [oxidecomputer/oxide.rs#458]
Seeing an error of `doesn't match pattern "^(?![0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)^[a-z][a-z0-9-]*[a-zA-Z0-9]*$"` technically tells me what is wrong but I hate debugging regexes. Arguably, the description from openapi is actually more useful

```
      "Name": {
        "title": "A name unique within the parent collection",
        "description": "Names must begin with a lower case ASCII letter, be composed exclusively of lowercase ASCII, uppercase ASCII, numbers, and '-', and may not end with a '-'. Names cannot be a UUID though they may contain a UUID.",
        "type": "string",
        "pattern": "^(?![0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)^[a-z][a-z0-9-]*[a-zA-Z0-9]*$",
        "minLength": 1,
        "maxLength": 63
      },
```

**Comment by david-crespo** [comment]
Analogous issue on the API side — I think CLI is just passing through the API’s bad error.

https://github.com/oxidecomputer/omicron/issues/1848

**Comment by david-crespo** [comment]
Actually no! The API error is way better 😁 The CLI should probably extract it and use it.

<img width="875" alt="image" src="https://github.com/oxidecomputer/oxide.rs/assets/3612203/c05ccf16-c120-4a09-82b5-3058a1b1e04f">

**Comment by ahl** [comment]
> Actually no! The API error is way better 😁 The CLI should probably extract it and use it.

I don't think it's feasible to extract: we can't even *make* a `Name` to send to the server!

We do something a little fancy for the CLI for `NameOrId`: https://github.com/oxidecomputer/oxide.rs/blob/6430c7ee628a5475466a68a08c16c45168a7fa09/sdk/src/clap_feature.rs#L116

I'll do something similar for Name.

I would love to do something generated, and I wrote about it here (at length!): https://github.com/oxidecomputer/typify/issues/456
