### ISSUE TITLE
Panic when pinging unauthenticated hosts

### ISSUE THREAD

**Issue by labbott** [oxidecomputer/oxide.rs#496]
### Component

- [X] CLI
- [ ] SDK
- [ ] Something else
- [ ] Not sure

### What was the expected behaviour

No panic when running `oxide ping` with no hosts

### What is the current behaviour and what actions did you take to get there

Set up a new machine, forgot to run login again,
```
labbott@labbott-desktop2:~$ oxide ping
thread 'tokio-runtime-worker' panicked at 'no authenticated hosts', cli/src/context.rs:28:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(21), ...)', cli/src/main.rs:63:10
```

### CLI or SDK version

0.2.0

### Operating system

Fedora

**Comment by ahl** [comment]
Gross. Thanks for reporting it; I'll take a look.
