### ISSUE TITLE
Proposal for version numbers for these crates

### ISSUE THREAD

**Issue by ahl** [oxidecomputer/oxide.rs#497]
There are 2 main artifacts in this repo: the CLI and the SDK. There's an ancillary artifact of the SDK mock library--assume that will follow the SDK.

For the both the CLI and the SDK there are two primary sources of breaking changes:
- Changes to the underlying API
- Changes to generation

(... and of course there are manual changes, but we'll set those aside for the moment.)

In both cases we will want to update the major version number. It's tempting to think that the SDK and CLI might have different version constraints, in particular that consumers of the CLI might not particularly care about the distinction between major versions as long as the corresponding API version is the same. This may not be the case for programmatic consumers of the CLI (i.e. scripts).

I propose that we use version numbers of the form: MAJOR.MINOR.PATH+APIVERSION. The last component (APIVERSION) would be descriptive, but important to help users identify the right version to use.

- In the case of a breaking change to the API itself or to generation, we'll rev the MAJOR
- In the case of a non-breaking change to the API or to generation (e.g. a bug fix), we'll rev the MINOR or PATCH
- Whenever the API version changes, we'll change the APIVERSION component

---

An alternative approach would be to use the API version as the CLI/SDK version. In this case, a breaking change from the generation would be tricky to handle (perhaps, wait until the next API version?).

Note that there isn't a necessity above that the SDK and CLI increment the MAJOR together. As SDK consumers and CLI consumers are unlikely to have much overlap, it seems fine that those might each have its own, unrelated version number according to the number of breaking changes its been through.

The SDK (and mock library) should be published to crates.io. I see no need to publish the CLI (especially as we move functionality from the CLI to the SDK per #452).

**Comment by david-crespo** [comment]
Sounds good to me. How would you define and detect a breaking change to the API or generation?

**Comment by ahl** [comment]
That's a good question. I think in general the versions from progenitor and the API might indicate breaking changes but I'm not sure. In practice most changes have been breaking so I don't think it hurts to err on the side of revving the major.
