### ISSUE TITLE
Small complaints about `auth` subcommand output

### ISSUE THREAD

**Issue by mkeeter** [oxidecomputer/oxide.rs#508]
### Target component

- [X] CLI
- [ ] SDK
- [ ] Something else
- [ ] Not sure

### Overview

I recently had to re-authenticated myself on the dogfood rack:
```
$ oxide auth status
https://[redacted]/: ["Not authenticated. Host/token combination invalid"]
```

I did so using `oxide auth login`:
```console 
$ oxide auth login --host=https://[redacted]/
You're already logged into https://[redacted]/
You're already logged into https://[redacted]/
Do you want to re-authenticate? yes
Opened this URL in your browser:
  https://[redacted]/device/verify

Enter the code: [redacted]

CurrentUser {
    display_name: "matt@oxidecomputer.com",
    id: cdd635aa-be19-407e-8787-583f76ff3636,
    silo_id: [redacted],
    silo_name: Name(
        "oxide",
    ),
}
Logged in as cdd635aa-be19-407e-8787-583f76ff3636
```

There are three issues with this output:

1) Telling me that I'm "already logged in" isn't helpful if that login is no longer valid; should we check validity and only print that message if the login is valid?
2) The message about me being already logged in is printed twice
3) The final message "Logged in as ..." should probably print my `display_name` instead of my `id`.

**Comment by ahl** [comment]
I believe this has been addressed by #727
