### ISSUE TITLE
reflector logic should only open a integration PR if files other than Cargo.lock are changed

### ISSUE THREAD

**Issue by ahl** [oxidecomputer/oxide.rs#510]
Today we open a new PR for the integrate branch on any change. This is fine and well, but there are *de minimis* changes e.g. to progenitor that don't merit a PR. Here's what I suggest:

- if there's a PR already open, update it
- otherwise, only open a new PR if there are file changes beyond `Cargo.lock`

The goal is to avoid PRs and commits that don't actually change the built artifacts. Not urgent, but I wanted to track this work.

cc: @augustuswm

**Comment by augustuswm** [comment]
That makes sense. I'll add this to my list.
