### ISSUE TITLE
Terminal cleanup for CLI can be better

### ISSUE THREAD

**Issue by taspelund** [oxidecomputer/oxide.rs#536]
### Component

- [X] CLI
- [ ] SDK
- [ ] Something else
- [ ] Not sure

### What was the expected behaviour

If a serial console session via the Oxide CLI gets hung or killed (`oxide instance serial console`), it doesn't always cleanup the terminal settings such that the shell initiating the session can be re-used.  It would be a much better experience for the user if their session continued to be usable when the oxide CLI process exits.

### What is the current behaviour and what actions did you take to get there

The terminal can be put into varying degrees of "janky" by running `oxide instance serial console --instance <UUID>` in one shell, and running `pkill -INT oxide` from a second shell.
Sometimes this results in the console going into raw mode, other times inputs like `Ctrl-C` are not accepted while arrow keys, Enter, and `Ctrl-D` work just fine.

### CLI or SDK version

```
➜  oxide-aarch64-apple-darwin ./oxide version
Oxide CLI 0.1.0-beta.5
Built from commit: 470f06dda83183413c24761580e3a19623e098c4
Oxide API: 0.0.1
```

### Operating system

MacOS

### Anything else you would like to add?

The proposal/request here is to improve the tty cleanup when the CLI process is killed by signals that are trappable and could reasonably be expected to be received.
e.g.
`SIGINT`, `SIGTERM`, `SIGQUIT`, `SIGHUP`

Note: this is not a request to gracefully handle signals like `SIGKILL`

**Comment by ahl** [comment]
@lifning can you take a look please?

**Comment by lifning** [comment]
On it! (This should be reasonably straightforward - the behavior we want is already in `impl Drop` for the "raw-mode guard" struct we use, just need to handle those signals appropriately & possibly also output the equivalent of `stty sane`)
