### ISSUE TITLE
`oxide auth status` looks like it's hanging when it isn't

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/oxide.rs#567]
### Component

- [X] CLI
- [ ] SDK
- [ ] Something else
- [ ] Not sure

### What was the expected behaviour

The help message says `oxide auth status` "verifies and displays information about your authentication state". That could mean (and I think it does mean) that it is actually hitting each configured host to test your creds. I think when I run it, it should print something immediately to say what it's doing. Ideally it would say "Verifying credentials for host abcdef.com..." immediately (maybe even with a spinner to indicate activity!), then print that result as soon as it comes back, and start on the next with a similar message. An less invasive improvement would be to just print _anything_ up front.

### What is the current behaviour and what actions did you take to get there

All I did was run `oxide auth status`.

I have three hosts configured and it sits here for 15 seconds before printing that they're all invalid. I suspect what it's doing is going through the three hosts serially and waiting 5 seconds for each request to time out before it decides they're broken, and then prints all three results at the end.

<img width="186" alt="image" src="https://github.com/oxidecomputer/oxide.rs/assets/3612203/e497b4b3-24be-4b0e-b5c2-37baa00cffa5">

### CLI or SDK version

Oxide CLI 0.2.0, built from commit: 7678a735c68863b4e1b1fbb5506335d9d7dc066e

### Operating system

macOS Sonoma 14.3.1

**Comment by david-crespo** [comment]
Or maybe it's doing them in parallel but with a 15s timeout.

https://github.com/oxidecomputer/oxide.rs/blob/d139868b875667cb420b05e546739b4fe1fb61f6/sdk/src/context.rs#L69

**Comment by ahl** [comment]
To confirm: yes, and this sucks.
