### ISSUE TITLE
Add option to connect to console when starting instance

### ISSUE THREAD

**Issue by taspelund** [oxidecomputer/oxide.rs#611]
### Target component

- [X] CLI
- [ ] SDK
- [ ] Something else
- [ ] Not sure

### Overview

Add an option to have the CLI open an instance's serial console when doing something like `oxide instance start` or `oxide instance from-image`.
e.g.
`oxide instance start --console`

**Comment by david-crespo** [comment]
I don't see how that's better than running `oxide instance serial console` after you run start — either way you have to know about it and do it. Adding a flag would also have the downside of requiring us to manually override the definition of `oxide instance start`, which is currently fully generated from the API schema. `from-image` is already a custom command, so it's easier on that one, but I still don't see the advantage.

Is the idea that you want to start the connection as soon as it's available so you don't miss the beginning? The [`serial console`](https://docs.oxide.computer/cli/instance/serial/console) command has a `-m` flag that lets you get a certain amount of history along with the live connection. There is also an [`oxide instance serial history`](https://docs.oxide.computer/cli/instance/serial/history).

I do think it would be a great idea to document an official way to do this, though, even if we don't change the CLI. Like "If you want to attach to the serial console immediately after starting the instance, run `oxide instance start [...args] && oxide instance serial console -m 100000`".

**Comment by ahl** [comment]
We can reopen if the suggestion above isn't sufficient
