### ISSUE TITLE
Need a new release of the CLI binaries for v7 new features and fixes

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/oxide.rs#620]
### Component

- [X] CLI
- [X] SDK
- [ ] Something else
- [ ] Not sure

### What was the expected behaviour

The first v7 customer update is scheduled for April 3 or 4th at this time. We'll need the CLI latest by April 2.

### What is the current behaviour and what actions did you take to get there

N/A

### CLI or SDK version

N/A

### Operating system

N/A

**Comment by ahl** [comment]
Boom goes the dynamite: https://github.com/oxidecomputer/oxide.rs/releases/tag/v0.4.0%2B20240327.0
