### ISSUE TITLE
disk requires special intervention to delete if upload process is Ctrl-C'd

### ISSUE THREAD

**Issue by faithanalog** [oxidecomputer/oxide.rs#651]
### Component

- [X] CLI
- [ ] SDK
- [ ] Something else
- [ ] Not sure

### What was the expected behaviour

If the upload process is interrupted, the disk receiving the upload should be deleted.

### What is the current behaviour and what actions did you take to get there

I was uploading a disk with the CLI:

```
oxide disk import --path $HOME/oxide/iodriver.iso --disk iodriver-4096 --project iodriver --description "iodriver" --snapshot iodriver-r4-snapshot-4096 --image iodriver-4096 --image-description "iodriver" --image-os nixos --image-version 23.11 --disk-block-size 4096
```

I `ctrl-c`'d this part way through on accident, interrupting the upload. At this point, the disk in the web interface displayed as `IMPORTING_FROM_BULK_WRITES`, and I could not delete it.

To make the disk delible, I used `oxide api` to manually move it along:

```
# indicate writes have stopped
oxide api -X POST /v1/disks/9943337a-c7cd-4e7b-8945-60aa2d585c64/bulk-write-stop

# finalize my half-uploaded image to a snapshot
echo '{ "snapshot_name": "ugh" }' | oxide api -X POST /v1/disks/9943337a-c7cd-4e7b-8945-60aa2d585c64/finalize --input -
```

As shown here, you need to tell it writing is done, which puts it into the state of waiting for finalization. Then you need to finalize it, which results in a created **snapshot**. At this point, the disk moves back to the `detached` state, and you can go delete the snapshot this created as well. These are steps the import process would have done automatically after finishing the upload, if it had been allowed to finish.

### CLI or SDK version

Oxide CLI 0.4.0+20240327.0 Built from commit: a55649b70e749ed2cd51877240200f81b35d0d3c  Oxide API: 20240327.0

### Operating system

illumos

### Anything else you would like to add?

This is a known behavior, which has also been brought up in https://github.com/oxidecomputer/omicron/issues/2987, an issue which tracks the problem that there is no "cancel import" state transition for a disk.

In that thread, it's been suggested to, for now, handle Ctrl-C by finalizing the disk, and then deleting the resulting disk/snapshot, a sort of "graceful shutdown" in this case. It wouldn't handle harder interruptions (network drop, reboot, etc.), but ctrl-c is easiest instance of this to hit right now.

**Comment by ahl** [comment]
@wfchandler can we close this now?

**Comment by wfchandler** [comment]
> [@wfchandler](https://github.com/wfchandler) can we close this now?

Yup, I'll close it out.
