### ISSUE TITLE
Add short hand commands "oxide inst l" for example

### ISSUE THREAD

**Issue by Smithx10** [oxidecomputer/oxide.rs#715]
### Target component

- [X] CLI
- [ ] SDK
- [ ] Something else
- [ ] Not sure

### Overview

While using the CLI I noticed "oxide inst" didn't work,  and  there didn't seem to be any short hands to cut down on typing.   I'd enjoy typing less.

**Comment by ahl** [comment]
How about this:

```console
$ oxide completion --shell bash > ox.bash
$ . ox.bash 
$ oxide inst<tab>
```

In fact, just `in<tab>` works and is even less typing.

**Comment by Smithx10** [comment]
With the completions it's good enough.
