### ISSUE TITLE
cannot perform other auth commands after `oxide auth logout -a`

### ISSUE THREAD

**Issue by elaine-oxide** [oxidecomputer/oxide.rs#797]
### Component

- [X] CLI
- [ ] SDK
- [ ] Something else
- [ ] Not sure

### What was the expected behaviour

I used the Oxide CLI to log out of all sessions, but due to the resulting state of the files in `~/.config/oxide`, it unexpectedly no longer allowed me to perform authentication-related actions.

### What is the current behaviour and what actions did you take to get there

- I was already logged in via `oxide auth login --host <url> --no-browser`, sometimes to multiple profiles.
- l logged out of everything via `oxide auth logout -a`
- Note this last command causes `~/.config/oxide/credentials.toml` to become empty, and `~/.config/oxide/config.toml ` unchanged (which means that `default-profile` now refers to a profile that doesn't exist).
- I can no longer perform further auth commands. Examples of commands that don't work:

```
% oxide auth status
TOML parse error at line 1, column 1
  |
1 | 
  | ^
missing field `profile`
``` 

```
% oxide auth login --host <url> --no-browser
TOML parse error at line 1, column 1
  |
1 | 
  | ^
missing field `profile`
```

- I got around this problem by removing the `~/.config/oxide` directory (by changing the directory name to another name), so that it would start over from scratch.

### CLI or SDK version

0.6.2+20240710.0

### Operating system

macOS 14.5

**Comment by david-crespo** [comment]
Nice, looks like it makes the file empty when it should be leaving something in there. Or the config parser should tolerate and empty list.

**Comment by elaine-oxide** [comment]
The same issue occurs when I have only logged into one host, and I log out of it with `oxide auth logout` (without the `-a` flag), and then I try to log in again to the same host.  Because `~/.config/oxide/credentials.toml` is empty, it stops with the same error.

```
% oxide auth login --host <host> --no-browser

% oxide auth logout

% oxide auth login --host <host> --no-browser
TOML parse error at line 1, column 1
  |
1 | 
  | ^
missing field `profile`

% oxide auth status
TOML parse error at line 1, column 1
  |
1 | 
  | ^
missing field `profile`
```

**Comment by elaine-oxide** [comment]
Thank you @wfchandler!  The fix works for me!  In this case I tried after regular `logout`, rather than after `logout -a`.
```
$ oxide version
Oxide CLI 0.7.0+20240821.0
Built from commit: 2101585acff7983e7b8b1fd5e6c757facf99d0fc 
Oxide API: 20240821.0
```
