### ISSUE TITLE
Use crates.io over git for dependencies

### ISSUE THREAD

**Issue by djacu** [oxidecomputer/oxide.rs#950]
## Problem

The presence of git dependencies can be problematic for build systems like Nix. `progenitor` as a git dependencies and `progenitor-client` as a registry causes the build to fail because it tries to vendor `progenitor-client` from two places: from crates.io as a direct dependency, and from GitHub as a transitive dependency of `progenitor`.

I would like to add `oxide-rs` to nixpkgs. Currently, I have a draft PR in using my fork and some modifications to make packaging possible and so @sarcasticadmin and I can test the CLI application. https://github.com/NixOS/nixpkgs/pull/366077

## Solution

- Use the registry for dependencies when possible. It is most important when a diamond dependency can be created as in the case of `progenitor`.
- Use the patch mechanism of cargo to change the source of dependencies during development. As is currently being done here: https://github.com/oxidecomputer/oxide.rs/blob/ed2163fb1159593fe2123d016f9fdbfa1acb6835/Cargo.toml#L91.

## Other

A secondary ask but not currently critical to resolving this issue. Please consider publishing `oxnet` and `thouart` to crates.io. It would make packaging the software in nixpkgs easier as we would not have to vendor the lock file.

**Comment by sarcasticadmin** [comment]
Thanks @ahl for the changes in https://github.com/oxidecomputer/oxide.rs/pull/952 

For releases after `0.9.0+20241204.0.0` we should be able to package oxide.rs in nixpkgs without having to do any extra patching.
